### ISSUE TITLE
Ошибка при фокусе на инпуте, на котором до этого было событие blur

### ISSUE THREAD

**Issue by zizi-shoot** [zizi-shoot/middle.messenger.praktikum.yandex#2]
В консоль падают ошибки при фокусе на инпуте, на котором ранее произошло событие _**blur**_
## Ожидаемое поведение
При событиях blur и focus срабатывают функции по очистке ошибок и валидации.

## Текущее поведение
Если сфокусироваться на инпуте, на котором перед этим сработал blur, то в консоли упадёт ошибка, и далее событие
фокуса вообще перестанет отрабатывать. Будет постоянно срабатывать blur и ошибка.

Трэйс ошибки 
```

Component.ts:156 Uncaught DOMException: Failed to execute 'replaceWith' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at http://localhost:3000/index.b71e74eb.js:657:18
    at Array.forEach (<anonymous>)
    at FormField.compile (http://localhost:3000/index.b71e74eb.js:654:47)
    at FormField._render (http://localhost:3000/index.b71e74eb.js:672:31)
    at http://localhost:3000/index.b71e74eb.js:12067:13
    at Array.forEach (<anonymous>)
    at EventBus.emit (http://localhost:3000/index.b71e74eb.js:12066:31)
    at FormField._componentDidUpdate (http://localhost:3000/index.b71e74eb.js:669:23)
    at http://localhost:3000/index.b71e74eb.js:12067:13
    at Array.forEach (<anonymous>)
```

## Шаги воспроизведения бага

https://user-images.githubusercontent.com/59991930/200663011-5f016737-ed79-4198-9d77-8433be692c80.mov

## Окружение
- macOS Ventura
- Google Chrome 107.0.5304.87 

**IMPORTANT!** В Safari и Firefox такой проблемы нет

## Возможные решения
на Stackoverflow есть [подобный вопрос](https://stackoverflow.com/questions/21926083/failed-to-execute-removechild-on-node) 8-летней давности с потенциальным объяснением проблемы и кучей советов, которые в моём случае не помогают либо не получается сделать.

**Comment by zizi-shoot** [comment]
Проблема как-то связана с тем, что во время ререндера дочерних элементов происходит странная ситуация: у дочернего элемента есть parentNode, а вот у этого parentNode уже нет данного дочернего элемента ¯\_(ツ)_/¯ Не до конца разобрался как там во всём этом участвует blur, но в качестве хоть какого-то решения сделал возможность навешивать события, которые отрабатывают только один раз (например **blur_once**). В таком случае бага не будет, но приходится заново вешать события при последующем фокусе.

**Comment by zizi-shoot** [comment]
убрал вообще обработку события focusin. Кажется можно им пренебречь, никакой важной функциональности оно не несёт
